# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdnATrw4t1m392WoMpaA9DE7rrc4wha0
"""

#Program 1
#Kondisi 1
teks = input("Masukkan Teks:")

#Hitung Kalimat
jumlah_kalimat = 0
for karakter in teks:
    if karakter == "." :
        jumlah_kalimat += 1
#Hitung Kata
jumlah_kata = 1
for karakter in teks :
    if karakter == " ":
        jumlah_kata += 1

print("Teks tersebut memuat", jumlah_kalimat, "kalimat dan", jumlah_kata, "kata.")

#Program 1
#Kondisi 2
teks = input("Masukkan Teks:")

#Hitung Kalimat
jumlah_kalimat = 0
for karakter in teks:
    if karakter == "." :
        jumlah_kalimat += 1
#Hitung Kata
jumlah_kata = 1
for karakter in teks :
    if karakter == " ":
        jumlah_kata += 1

print("Teks tersebut memuat", jumlah_kalimat, "kalimat dan", jumlah_kata, "kata.")

#Program 1
#Kondisi 3
teks = input("Masukkan Teks:")

#Hitung Kalimat
jumlah_kalimat = 0
for karakter in teks:
    if karakter == "." :
        jumlah_kalimat += 1
#Hitung Kata
jumlah_kata = 1
for karakter in teks :
    if karakter == " ":
        jumlah_kata += 1

print("Teks tersebut memuat", jumlah_kalimat, "kalimat dan", jumlah_kata, "kata.")