# -*- coding: utf-8 -*-
"""04_NIP_ASN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VktQ8WV9iBq_e6FmxqOBdYIWjqGE76Yp
"""

#Program NIP_ASN
#Skenario 1 :199410212019031010
#Skenario 2 :200002292022011002
#Skenario 3 :200302292024011004
#Skenario 1
#Inisialisasi kamus bulan dan batas hari
data_bulan = {
    1:"Januari", 2:"Februari", 3:"Maret", 4:"April", 5:"Mei", 6:"Juni",
    7:"Juli", 8:"Agustus", 9:"September", 10:"Oktober", 11:"November",
    12:"Desember"
}
data_hari = {
    1:31, 2:28, 3:31, 4:30, 5:31, 6:30,
    7:31, 8:31, 9:30, 10:31, 11:30,
    12:31
}

while True:
  NIP = input("Masukkan 18 digit NIP Anda:")
  tahun = int(NIP[0:4]) #Indeks Python mulai dari 0
  bulan = int(NIP[4:6])
  tanggal = int(NIP[6:8])

  #Validasi rentang bulan
  if bulan < 1 or bulan > 12:
    print("NIP tidak valid, harap masukkan ulang.")
    continue 
  #Mengambil data dari kamus
  nama_bulan = data_bulan[bulan]
  max_hari = data_hari[bulan]

  #Cek tahun kabisat (update batas Februari)
  if bulan == 2 and (tahun % 400 == 0 or (tahun % 4 == 0 and tahun % 100 != 0)):
    max_hari = 29

  #Validasi batas tanggal
  if tanggal <1 or tanggal > max_hari:
    print("NIP tidak valid, harap masukkan ulang.")
    continue 

  #Jika semua valid
  print("Tanggal lahir Anda:", tanggal, nama_bulan, tahun)
  break

#Skenario 2
#Inisialisasi kamus bulan dan batas hari
data_bulan = {
    1:"Januari", 2:"Februari", 3:"Maret", 4:"April", 5:"Mei", 6:"Juni",
    7:"Juli", 8:"Agustus", 9:"September", 10:"Oktober", 11:"November",
    12:"Desember"
}
data_hari = {
    1:31, 2:28, 3:31, 4:30, 5:31, 6:30,
    7:31, 8:31, 9:30, 10:31, 11:30,
    12:31
}

while True:
  NIP = input("Masukkan 18 digit NIP Anda:")
  tahun = int(NIP[0:4]) #Indeks Python mulai dari 0
  bulan = int(NIP[4:6])
  tanggal = int(NIP[6:8])

  #Validasi rentang bulan
  if bulan < 1 or bulan > 12:
    print("NIP tidak valid, harap masukkan ulang.")
    continue 

  #Mengambil data dari kamus
  nama_bulan = data_bulan[bulan]
  max_hari = data_hari[bulan]

  #Cek tahun kabisat (update batas Februari)
  if bulan == 2 and (tahun % 400 == 0 or (tahun % 4 == 0 and tahun % 100 != 0)):
    max_hari = 29

  #Validasi batas tanggal
  if tanggal <1 or tanggal > max_hari:
    print("NIP tidak valid, harap masukkan ulang.")
    continue 

  #Jika semua valid
  print("Tanggal lahir Anda:", tanggal, nama_bulan, tahun)
  break

#Skenario 3
#Inisialisasi kamus bulan dan batas hari
data_bulan = {
    1:"Januari", 2:"Februari", 3:"Maret", 4:"April", 5:"Mei", 6:"Juni",
    7:"Juli", 8:"Agustus", 9:"September", 10:"Oktober", 11:"November",
    12:"Desember"
}
data_hari = {
    1:31, 2:28, 3:31, 4:30, 5:31, 6:30,
    7:31, 8:31, 9:30, 10:31, 11:30,
    12:31
}

while True:
  NIP = input("Masukkan 18 digit NIP Anda:")
  tahun = int(NIP[0:4]) #Indeks Python mulai dari 0
  bulan = int(NIP[4:6])
  tanggal = int(NIP[6:8])

  #Validasi rentang bulan
  if bulan < 1 or bulan > 12:
    print("NIP tidak valid, harap masukkan ulang.")
    continue 

  #Mengambil data dari kamus
  nama_bulan = data_bulan[bulan]
  max_hari = data_hari[bulan]

  #Cek tahun kabisat (update batas Februari)
  if bulan == 2 and (tahun % 400 == 0 or (tahun % 4 == 0 and tahun % 100 != 0)):
    max_hari = 29

  #Validasi batas tanggal
  if tanggal <1 or tanggal > max_hari:
    print("NIP tidak valid, harap masukkan ulang.")
    continue 

  #Jika semua valid
  print("Tanggal lahir Anda:", tanggal, nama_bulan, tahun)
  break
