# -*- coding: utf-8 -*-
"""Program 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zW8mbdKpd9LqyPZDdG2gCLwfz6sbcHHW
"""

import math

def tentukan_cluster(x1, x2, x3):

    # KONDISI 1: Validasi Error Input (Bukan Angka)
    # Memeriksa apakah ada parameter yang bukan int atau float
    if not (isinstance(x1, (int, float)) and
            isinstance(x2, (int, float)) and
            isinstance(x3, (int, float))):
        print(f"Menguji Titik U: ({x1}, {x2}, {x3})")
        print("Hasil: KONDISI ERROR (Input harus berupa angka!)\n")
        return # Keluar dari fungsi dengan aman

    # Tetapkan koordinat pusat cluster tetap
    A = (2, 1, 3)
    B = (1, -4, 6)
    C = (-2, 3, -2)

    # Fungsi internal untuk menghitung jarak Euclidean
    def hitung_jarak(titik1, titik2):
        return math.sqrt((titik1[0] - titik2[0])**2 +
                         (titik1[1] - titik2[1])**2 +
                         (titik1[2] - titik2[2])**2)

    # Hitung jarak dari U ke setiap cluster
    U = (x1, x2, x3)
    jarak_A = hitung_jarak(U, A)
    jarak_B = hitung_jarak(U, B)
    jarak_C = hitung_jarak(U, C)

    # Cetak informasi titik dan jarak (Gunakan format .7f agar presisi desimalnya terlihat)
    print(f"Menguji Titik U: ({x1:.7f}, {x2:.7f}, {x3:.7f})")
    print(f"- Jarak ke Cluster A: {jarak_A:.4f}")
    print(f"- Jarak ke Cluster B: {jarak_B:.4f}")
    print(f"- Jarak ke Cluster C: {jarak_C:.4f}")

    # KONDISI 2: Kondisi Khusus (Deteksi Cluster yang Jaraknya Sama)
    # Ditambahkan pembulatan mikro (round) agar toleransi limit angka pecahan di komputer aman
    jA, jB, jC = round(jarak_A, 7), round(jarak_B, 7), round(jarak_C, 7)

    if jA == jB and jB == jC:
        print("Hasil: KONDISI KHUSUS (Titik U berada tepat di tengah-tengah antara Cluster A, B, dan C)\n")
    elif jA == jB and jA <= jC:
        print("Hasil: KONDISI KHUSUS (Titik U memiliki jarak terdekat yang SAMA antara CLUSTER A dan CLUSTER B)\n")
    elif jA == jC and jA <= jB:
        print("Hasil: KONDISI KHUSUS (Titik U memiliki jarak terdekat yang SAMA antara CLUSTER A dan CLUSTER C)\n")
    elif jB == jC and jB <= jA:
        print("Hasil: KONDISI KHUSUS (Titik U memiliki jarak terdekat yang SAMA antara CLUSTER B dan CLUSTER C)\n")

    # KONDISI 3: Kondisi Normal (Satu Cluster Terdekat)
    elif jA < jB and jA < jC:
        print("Hasil: KONDISI NORMAL (CLUSTER A)\n")
    elif jB < jC:
        print("Hasil: KONDISI NORMAL (CLUSTER B)\n")
    else:
        print("Hasil: KONDISI NORMAL (CLUSTER C)\n")


# UJI COBA
tentukan_cluster(0, 2, 0.5)
tentukan_cluster(-1, 2, -1)
tentukan_cluster("Lanang", 3, 5)