# -*- coding: utf-8 -*-
"""06_interval_proporsi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoFFe4a2mHiXTaeCMYxtx42qMW-Qt86_
"""

import math

def hitung_interval_konfidensi(p_hat, n, alpha):
    try:
        # Konversi input ke tipe data yang sesuai
        p_hat = float(p_hat)
        n = int(n)
        alpha = float(alpha)
        print("--- Program Interval Konfidensi ---")

        # VALIDASI INPUT
        if p_hat < 0 or p_hat > 1:
            print("Error: Proporsi (p_hat) harus berada di antara 0 dan 1.")
        elif n <= 0:
            print("Error: Ukuran sampel (n) harus lebih besar dari 0.")
        elif alpha != 0.10 and alpha != 0.05:
            print("Error: Nilai alpha harus 0.10 atau 0.05.")
        else:
            # Penentuan nilai z
            z = 1.645 if alpha == 0.10 else 1.96

            # Perhitungan Margin of Error
            margin_of_error = z * math.sqrt((p_hat * (1 - p_hat)) / n)

            batas_bawah = p_hat - margin_of_error
            batas_atas = p_hat + margin_of_error

            # Output hasil
            print("\n--- Hasil Perhitungan ---")
            print(f"Interval Konfidensi ({(1 - alpha) * 100:.0f}%): "
                  f"{batas_bawah:.4f} < p < {batas_atas:.4f}")

    except ValueError:
        # Menangani jika user memasukkan teks (bukan angka)
        print("Error: Input harus berupa angka yang valid.")

# Jalankan program
if __name__ == "__main__":
    hitung_interval_konfidensi(0.5,100,0.05)
    hitung_interval_konfidensi(0.5,100,0.1)
    hitung_interval_konfidensi(0.5,100,0.2)
    hitung_interval_konfidensi(1.2,100,0.05)